apiVersion: skaffold/v4beta8
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
    - ./infra/k8s-dev/*
deploy:
  kubectl: {}
build:
  local:
    push: true
  artifacts:
    - image: markmorcos/auth
      context: auth
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: markmorcos/tickets
      context: tickets
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: markmorcos/orders
      context: orders
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: markmorcos/expiration
      context: expiration
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: markmorcos/payments
      context: payments
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: markmorcos/client
      context: client
      sync:
        manual:
          - src: "**/*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
